
* other clients
http://primordiax.com/play/client.html
http://www.avenshar.com/client/client.html?t=1284693878389
http://maidendesmodus.com/play/
* bugs
** TODO if you go into command history, and change the command before resubmitting it, the changed copy is cached back in the cmd history (cuz it restores whatever is on the line)
** TODO the character representing a road which enters at the bottom of the tile and exits to the right doesnt display, and it messes up the map


* script planning

** high level:
*** scripts are javascript
*** users /read scripts in using ajax requests
*** no /write
*** no creating any scripts in client at all??  no /alias, /macro
*** client exposes a javascript API for scripts /read from ajax
**** e.g. with mud_client.api, alias( text, cmd), etc.
*** errors in /read script would be displayed in terminal
*** what if they want stuff on the fly?? this is a significant use case
**** option: allow raw javascript input on command line
***** e.g. /script alias("sv","c shockw")
**** option: pop-up a mini javascript editor. dont really want to encourage popups ever.
*** what if they want to persist script elements they have typed in command line?
**** option: store /script commands into a temp buffer


** initiates script activity:
*** running of alias
*** running of macro
*** firing of trigger

** commands



* alias planning
** /alias { text } { cmd }   ->  new_alias

* help files
** alias
Format: /alias shortcut commands group name

An alias lets you define some "shortcut" text to execute a command or commands.
Your alias list is checked each time you press enter to send some text to the
mud. If the text you typed is found in your alias list the text from the
commands side of the alias is sent instead.  An alias is only replaced if it is
the first text typed on a line.

   þ alias name This is the shortcut text you want to be able to type to
     execute commands.
   þ commands The commands to execute when the alias name is typed.
   þ group name This is an optional parameter. See the user guide on groups
     for help.

Examples:

/alias eat take food bag;gobble food
If you typed "eat" on the input line the commands "take food bag" and "gobble
food" would be sent to the mud instead.

/alias targ %0 /var Target $0
You can also use the variable %0 to represent the text typed after the alias
shortcut. In this case the alias is used to quickly set a targeting variable.
Typing "targ Vecna" would set a variable called "Target" to "Vecna"
